### ISSUE TITLE
Please could you add my robot? :)

### ISSUE THREAD

**Issue by JoshPattman** [beduffy/all-quadrupeds#1]
Please could you add my quadruped (called spotpuppy)
Instagram account: https://instagram.com/spotpuppyrobot?utm_medium=copy_link
GitHub: github.com/joshpattman/spotpuppy

**Comment by JoshPattman** [comment]
Actually I've just noticed some links to spotpuppy are in there but under a different name with someone else's robot (I'm josh pattman not josh pieper), also the website link with blizzardfishstudios is outdated, I'm going to start posting updates on the Instagram instead.

**Comment by beduffy** [comment]
Hi, thanks for your message. I have recently added spotpuppy GitHub and your blizzardfishstudios four legged walking blog (I enjoyed reading it). If you want me to remove the blizzardfish link, I can. Adding the instagram now. 
I don't think I mixed up the Josh Pieper name on youtube and github, he creates the A1 quadruped. Unless you're referring to another link.

**Comment by JoshPattman** [comment]
Thanks. Also yeah actually sorry I think I misread the document :)
